CREATE TABLE devices(
  id serial PRIMARY KEY NOT NULL ,
  product_channel_id INTEGER,
  platform VARCHAR (255),
  platform_version VARCHAR (255),
  version_code VARCHAR (255),
  version_name VARCHAR (255),
  sid VARCHAR (255),
  ua VARCHAR (255),
  imei VARCHAR (255),
  imsi VARCHAR (255),
  active_num INTEGER,
  reg_num INTEGER,
  status INTEGER,
  fr VARCHAR (255),
  ip VARCHAR (255),
  manufacturer VARCHAR (255),
  model VARCHAR (255),
  created_at INTEGER,
  partner_id INTEGER,
  login_num INTEGER DEFAULT 0,
  device_no VARCHAR (255),
  push_token VARCHAR (255),
  idfa VARCHAR (255),
  last_at INTEGER,
  user_id INTEGER,
  client_status INTEGER,
  phone_number VARCHAR (255),
  latitude INTEGER,
  longitude INTEGER,
  geo_province_id INTEGER,
  geo_city_id INTEGER,
  province_id INTEGER,
  city_id INTEGER,
  net VARCHAR (255),
  sdks VARCHAR (255),
  api_version VARCHAR (255),
  finger text,
  mem_size VARCHAR (255),
  storage_size VARCHAR (255),
  ava_storage_size VARCHAR (255),
  dns VARCHAR (255),
  is_root INTEGER,
  idfv VARCHAR (255),
  tele_name VARCHAR (255),
  tele_num VARCHAR (255),
  is_simulator INTEGER,
  seria_no VARCHAR (255),
  local_mac VARCHAR (255),
  gateway_mac VARCHAR (255)
);