insert into provinces (id, name) values (1,'北京');
insert into provinces (id, name) values (2,'上海');
insert into provinces (id, name) values (3,'天津');
insert into provinces (id, name) values (4,'重庆');
insert into provinces (id, name) values (5,'河北');
insert into provinces (id, name) values (6,'山西');
insert into provinces (id, name) values (7,'河南');
insert into provinces (id, name) values (8,'辽宁');
insert into provinces (id, name) values (9,'吉林');
insert into provinces (id, name) values (10,'黑龙江');
insert into provinces (id, name) values (11,'内蒙古');
insert into provinces (id, name) values (12,'江苏');
insert into provinces (id, name) values (13,'山东');
insert into provinces (id, name) values (14,'安徽');
insert into provinces (id, name) values (15,'浙江');
insert into provinces (id, name) values (16,'福建');
insert into provinces (id, name) values (17,'湖北');
insert into provinces (id, name) values (18,'湖南');
insert into provinces (id, name) values (19,'广东');
insert into provinces (id, name) values (20,'广西');
insert into provinces (id, name) values (21,'江西');
insert into provinces (id, name) values (22,'四川');
insert into provinces (id, name) values (23,'海南');
insert into provinces (id, name) values (24,'贵州');
insert into provinces (id, name) values (25,'云南');
insert into provinces (id, name) values (26,'西藏');
insert into provinces (id, name) values (27,'陕西');
insert into provinces (id, name) values (28,'甘肃');
insert into provinces (id, name) values (29,'青海');
insert into provinces (id, name) values (30,'宁夏');
insert into provinces (id, name) values (31,'新疆');
insert into provinces (id, name) values (32,'台湾');
insert into provinces (id, name) values (33,'香港');
insert into provinces (id, name) values (34,'澳门');
insert into cities (id, province_id, name) values (1, 1, '北京');
 insert into cities (id, province_id, name) values (2, 2, '上海');
 insert into cities (id, province_id, name) values (3, 3, '天津');
 insert into cities (id, province_id, name) values (4, 4, '重庆');
 insert into cities (id, province_id, name) values (5, 5, '石家庄市');
 insert into cities (id, province_id, name) values (6, 5, '邯郸市');
 insert into cities (id, province_id, name) values (7, 5, '邢台市');
 insert into cities (id, province_id, name) values (8, 5, '保定市');
 insert into cities (id, province_id, name) values (9, 5, '张家口市');
 insert into cities (id, province_id, name) values (10, 5, '承德市');
 insert into cities (id, province_id, name) values (11, 5, '秦皇岛市');
 insert into cities (id, province_id, name) values (12, 5, '唐山市');
 insert into cities (id, province_id, name) values (13, 5, '沧州市');
 insert into cities (id, province_id, name) values (14, 5, '廊坊市');
 insert into cities (id, province_id, name) values (15, 5, '衡水市');
 insert into cities (id, province_id, name) values (16, 6, '太原市');
 insert into cities (id, province_id, name) values (17, 6, '大同市');
 insert into cities (id, province_id, name) values (18, 6, '阳泉市');
 insert into cities (id, province_id, name) values (19, 6, '晋城市');
 insert into cities (id, province_id, name) values (20, 6, '朔州市');
 insert into cities (id, province_id, name) values (21, 6, '晋中市');
 insert into cities (id, province_id, name) values (22, 6, '忻州市');
 insert into cities (id, province_id, name) values (23, 6, '吕梁市');
 insert into cities (id, province_id, name) values (24, 6, '临汾市');
 insert into cities (id, province_id, name) values (25, 6, '运城市');
 insert into cities (id, province_id, name) values (26, 6, '长治市');
 insert into cities (id, province_id, name) values (27, 7, '郑州市');
 insert into cities (id, province_id, name) values (28, 7, '开封市');
 insert into cities (id, province_id, name) values (29, 7, '洛阳市');
 insert into cities (id, province_id, name) values (30, 7, '平顶山市');
 insert into cities (id, province_id, name) values (31, 7, '焦作市');
 insert into cities (id, province_id, name) values (32, 7, '鹤壁市');
 insert into cities (id, province_id, name) values (33, 7, '新乡市');
 insert into cities (id, province_id, name) values (34, 7, '安阳市');
 insert into cities (id, province_id, name) values (35, 7, '濮阳市');
 insert into cities (id, province_id, name) values (36, 7, '许昌市');
 insert into cities (id, province_id, name) values (37, 7, '漯河市');
 insert into cities (id, province_id, name) values (38, 7, '三门峡市');
 insert into cities (id, province_id, name) values (39, 7, '南阳市');
 insert into cities (id, province_id, name) values (40, 7, '商丘市');
 insert into cities (id, province_id, name) values (41, 7, '周口市');
 insert into cities (id, province_id, name) values (42, 7, '驻马店市');
 insert into cities (id, province_id, name) values (43, 7, '信阳市');
 insert into cities (id, province_id, name) values (44, 7, '济源市');
 insert into cities (id, province_id, name) values (45, 8, '沈阳市');
 insert into cities (id, province_id, name) values (46, 8, '大连市');
 insert into cities (id, province_id, name) values (47, 8, '鞍山市');
 insert into cities (id, province_id, name) values (48, 8, '抚顺市');
 insert into cities (id, province_id, name) values (49, 8, '本溪市');
 insert into cities (id, province_id, name) values (50, 8, '丹东市');
 insert into cities (id, province_id, name) values (51, 8, '锦州市');
 insert into cities (id, province_id, name) values (52, 8, '葫芦岛市');
 insert into cities (id, province_id, name) values (53, 8, '营口市');
 insert into cities (id, province_id, name) values (54, 8, '盘锦市');
 insert into cities (id, province_id, name) values (55, 8, '阜新市');
 insert into cities (id, province_id, name) values (56, 8, '辽阳市');
 insert into cities (id, province_id, name) values (57, 8, '朝阳市');
 insert into cities (id, province_id, name) values (58, 8, '铁岭市');
 insert into cities (id, province_id, name) values (59, 9, '长春市');
 insert into cities (id, province_id, name) values (60, 9, '吉林市');
 insert into cities (id, province_id, name) values (61, 9, '四平市');
 insert into cities (id, province_id, name) values (62, 9, '辽源市');
 insert into cities (id, province_id, name) values (63, 9, '通化市');
 insert into cities (id, province_id, name) values (64, 9, '白山市');
 insert into cities (id, province_id, name) values (65, 9, '松原市');
 insert into cities (id, province_id, name) values (66, 9, '白城市');
 insert into cities (id, province_id, name) values (67, 9, '延边州');
 insert into cities (id, province_id, name) values (68, 10, '鹤岗市');
 insert into cities (id, province_id, name) values (69, 10, '双鸭山市');
 insert into cities (id, province_id, name) values (70, 10, '鸡西市');
 insert into cities (id, province_id, name) values (71, 10, '大庆市');
 insert into cities (id, province_id, name) values (72, 10, '伊春市');
 insert into cities (id, province_id, name) values (73, 10, '牡丹江市');
 insert into cities (id, province_id, name) values (74, 10, '佳木斯市');
 insert into cities (id, province_id, name) values (75, 10, '七台河市');
 insert into cities (id, province_id, name) values (76, 10, '黑河市');
 insert into cities (id, province_id, name) values (77, 10, '绥化市');
 insert into cities (id, province_id, name) values (78, 10, '大兴安岭地区');
 insert into cities (id, province_id, name) values (79, 10, '哈尔滨市');
 insert into cities (id, province_id, name) values (80, 10, '齐齐哈尔市');
 insert into cities (id, province_id, name) values (81, 11, '呼和浩特市');
 insert into cities (id, province_id, name) values (82, 11, '包头市');
 insert into cities (id, province_id, name) values (83, 11, '乌海市');
 insert into cities (id, province_id, name) values (84, 11, '赤峰市');
 insert into cities (id, province_id, name) values (85, 11, '乌兰察布市');
 insert into cities (id, province_id, name) values (86, 11, '锡林郭勒盟');
 insert into cities (id, province_id, name) values (87, 11, '呼伦贝尔市');
 insert into cities (id, province_id, name) values (88, 11, '鄂尔多斯市');
 insert into cities (id, province_id, name) values (89, 11, '巴彦淖尔市');
 insert into cities (id, province_id, name) values (90, 11, '阿拉善盟');
 insert into cities (id, province_id, name) values (91, 11, '兴安盟');
 insert into cities (id, province_id, name) values (92, 11, '通辽市');
 insert into cities (id, province_id, name) values (93, 12, '南京市');
 insert into cities (id, province_id, name) values (94, 12, '徐州市');
 insert into cities (id, province_id, name) values (95, 12, '连云港市');
 insert into cities (id, province_id, name) values (96, 12, '淮安市');
 insert into cities (id, province_id, name) values (97, 12, '宿迁市');
 insert into cities (id, province_id, name) values (98, 12, '盐城市');
 insert into cities (id, province_id, name) values (99, 12, '扬州市');
 insert into cities (id, province_id, name) values (100, 12, '泰州市');
 insert into cities (id, province_id, name) values (101, 12, '南通市');
 insert into cities (id, province_id, name) values (102, 12, '镇江市');
 insert into cities (id, province_id, name) values (103, 12, '常州市');
 insert into cities (id, province_id, name) values (104, 12, '无锡市');
 insert into cities (id, province_id, name) values (105, 12, '苏州市');
 insert into cities (id, province_id, name) values (106, 13, '济宁市');
 insert into cities (id, province_id, name) values (107, 13, '济南市');
 insert into cities (id, province_id, name) values (108, 13, '青岛市');
 insert into cities (id, province_id, name) values (109, 13, '淄博市');
 insert into cities (id, province_id, name) values (110, 13, '枣庄市');
 insert into cities (id, province_id, name) values (111, 13, '东营市');
 insert into cities (id, province_id, name) values (112, 13, '潍坊市');
 insert into cities (id, province_id, name) values (113, 13, '烟台市');
 insert into cities (id, province_id, name) values (114, 13, '威海市');
 insert into cities (id, province_id, name) values (115, 13, '莱芜市');
 insert into cities (id, province_id, name) values (116, 13, '德州市');
 insert into cities (id, province_id, name) values (117, 13, '临沂市');
 insert into cities (id, province_id, name) values (118, 13, '聊城市');
 insert into cities (id, province_id, name) values (119, 13, '滨州市');
 insert into cities (id, province_id, name) values (120, 13, '菏泽市');
 insert into cities (id, province_id, name) values (121, 13, '日照市');
 insert into cities (id, province_id, name) values (122, 13, '泰安市');
 insert into cities (id, province_id, name) values (123, 14, '黄山市');
 insert into cities (id, province_id, name) values (124, 14, '滁州市');
 insert into cities (id, province_id, name) values (125, 14, '阜阳市');
 insert into cities (id, province_id, name) values (126, 14, '亳州市');
 insert into cities (id, province_id, name) values (127, 14, '宿州市');
 insert into cities (id, province_id, name) values (128, 14, '池州市');
 insert into cities (id, province_id, name) values (129, 14, '六安市');
 insert into cities (id, province_id, name) values (130, 14, '宣城市');
 insert into cities (id, province_id, name) values (131, 14, '铜陵市');
 insert into cities (id, province_id, name) values (132, 14, '合肥市');
 insert into cities (id, province_id, name) values (133, 14, '淮南市');
 insert into cities (id, province_id, name) values (134, 14, '淮北市');
 insert into cities (id, province_id, name) values (135, 14, '芜湖市');
 insert into cities (id, province_id, name) values (136, 14, '蚌埠市');
 insert into cities (id, province_id, name) values (137, 14, '马鞍山市');
 insert into cities (id, province_id, name) values (138, 14, '安庆市');
 insert into cities (id, province_id, name) values (139, 15, '宁波市');
 insert into cities (id, province_id, name) values (140, 15, '衢州市');
 insert into cities (id, province_id, name) values (141, 15, '丽水市');
 insert into cities (id, province_id, name) values (142, 15, '台州市');
 insert into cities (id, province_id, name) values (143, 15, '舟山市');
 insert into cities (id, province_id, name) values (144, 15, '杭州市');
 insert into cities (id, province_id, name) values (145, 15, '温州市');
 insert into cities (id, province_id, name) values (146, 15, '嘉兴市');
 insert into cities (id, province_id, name) values (147, 15, '湖州市');
 insert into cities (id, province_id, name) values (148, 15, '绍兴市');
 insert into cities (id, province_id, name) values (149, 15, '金华市');
 insert into cities (id, province_id, name) values (150, 16, '福州市');
 insert into cities (id, province_id, name) values (151, 16, '厦门市');
 insert into cities (id, province_id, name) values (152, 16, '三明市');
 insert into cities (id, province_id, name) values (153, 16, '莆田市');
 insert into cities (id, province_id, name) values (154, 16, '泉州市');
 insert into cities (id, province_id, name) values (155, 16, '漳州市');
 insert into cities (id, province_id, name) values (156, 16, '南平市');
 insert into cities (id, province_id, name) values (157, 16, '龙岩市');
 insert into cities (id, province_id, name) values (158, 16, '宁德市');
 insert into cities (id, province_id, name) values (159, 17, '孝感市');
 insert into cities (id, province_id, name) values (160, 17, '黄冈市');
 insert into cities (id, province_id, name) values (161, 17, '咸宁市');
 insert into cities (id, province_id, name) values (162, 17, '恩施州');
 insert into cities (id, province_id, name) values (163, 17, '鄂州市');
 insert into cities (id, province_id, name) values (164, 17, '荆门市');
 insert into cities (id, province_id, name) values (165, 17, '随州市');
 insert into cities (id, province_id, name) values (166, 17, '神农架林区');
 insert into cities (id, province_id, name) values (167, 17, '武汉市');
 insert into cities (id, province_id, name) values (168, 17, '黄石市');
 insert into cities (id, province_id, name) values (169, 17, '襄阳市');
 insert into cities (id, province_id, name) values (170, 17, '十堰市');
 insert into cities (id, province_id, name) values (171, 17, '荆州市');
 insert into cities (id, province_id, name) values (172, 17, '宜昌市');
 insert into cities (id, province_id, name) values (173, 17, '潜江市');
 insert into cities (id, province_id, name) values (174, 17, '天门市');
 insert into cities (id, province_id, name) values (175, 17, '仙桃市');
 insert into cities (id, province_id, name) values (176, 18, '耒阳市');
 insert into cities (id, province_id, name) values (177, 18, '长沙市');
 insert into cities (id, province_id, name) values (178, 18, '株洲市');
 insert into cities (id, province_id, name) values (179, 18, '湘潭市');
 insert into cities (id, province_id, name) values (180, 18, '韶山市');
 insert into cities (id, province_id, name) values (181, 18, '衡阳市');
 insert into cities (id, province_id, name) values (182, 18, '邵阳市');
 insert into cities (id, province_id, name) values (183, 18, '岳阳市');
 insert into cities (id, province_id, name) values (184, 18, '常德市');
 insert into cities (id, province_id, name) values (185, 18, '张家界市');
 insert into cities (id, province_id, name) values (186, 18, '郴州市');
 insert into cities (id, province_id, name) values (187, 18, '益阳市');
 insert into cities (id, province_id, name) values (188, 18, '永州市');
 insert into cities (id, province_id, name) values (189, 18, '怀化市');
 insert into cities (id, province_id, name) values (190, 18, '娄底市');
 insert into cities (id, province_id, name) values (191, 18, '湘西州');
 insert into cities (id, province_id, name) values (192, 19, '广州市');
 insert into cities (id, province_id, name) values (193, 19, '深圳市');
 insert into cities (id, province_id, name) values (194, 19, '珠海市');
 insert into cities (id, province_id, name) values (195, 19, '汕头市');
 insert into cities (id, province_id, name) values (196, 19, '韶关市');
 insert into cities (id, province_id, name) values (197, 19, '河源市');
 insert into cities (id, province_id, name) values (198, 19, '梅州市');
 insert into cities (id, province_id, name) values (199, 19, '揭阳市');
 insert into cities (id, province_id, name) values (200, 19, '惠州市');
 insert into cities (id, province_id, name) values (201, 19, '汕尾市');
 insert into cities (id, province_id, name) values (202, 19, '东莞市');
 insert into cities (id, province_id, name) values (203, 19, '中山市');
 insert into cities (id, province_id, name) values (204, 19, '江门市');
 insert into cities (id, province_id, name) values (205, 19, '佛山市');
 insert into cities (id, province_id, name) values (206, 19, '阳江市');
 insert into cities (id, province_id, name) values (207, 19, '湛江市');
 insert into cities (id, province_id, name) values (208, 19, '茂名市');
 insert into cities (id, province_id, name) values (209, 19, '肇庆市');
 insert into cities (id, province_id, name) values (210, 19, '云浮市');
 insert into cities (id, province_id, name) values (211, 19, '清远市');
 insert into cities (id, province_id, name) values (212, 19, '潮州市');
 insert into cities (id, province_id, name) values (213, 20, '崇左市');
 insert into cities (id, province_id, name) values (214, 20, '南宁市');
 insert into cities (id, province_id, name) values (215, 20, '柳州市');
 insert into cities (id, province_id, name) values (216, 20, '桂林市');
 insert into cities (id, province_id, name) values (217, 20, '梧州市');
 insert into cities (id, province_id, name) values (218, 20, '北海市');
 insert into cities (id, province_id, name) values (219, 20, '防城港市');
 insert into cities (id, province_id, name) values (220, 20, '钦州市');
 insert into cities (id, province_id, name) values (221, 20, '贵港市');
 insert into cities (id, province_id, name) values (222, 20, '玉林市');
 insert into cities (id, province_id, name) values (223, 20, '贺州市');
 insert into cities (id, province_id, name) values (224, 20, '百色市');
 insert into cities (id, province_id, name) values (225, 20, '河池市');
 insert into cities (id, province_id, name) values (226, 20, '来宾市');
 insert into cities (id, province_id, name) values (227, 21, '南昌市');
 insert into cities (id, province_id, name) values (228, 21, '景德镇市');
 insert into cities (id, province_id, name) values (229, 21, '萍乡市');
 insert into cities (id, province_id, name) values (230, 21, '新余市');
 insert into cities (id, province_id, name) values (231, 21, '九江市');
 insert into cities (id, province_id, name) values (232, 21, '鹰潭市');
 insert into cities (id, province_id, name) values (233, 21, '上饶市');
 insert into cities (id, province_id, name) values (234, 21, '宜春市');
 insert into cities (id, province_id, name) values (235, 21, '抚州市');
 insert into cities (id, province_id, name) values (236, 21, '吉安市');
 insert into cities (id, province_id, name) values (237, 21, '赣州市');
 insert into cities (id, province_id, name) values (238, 22, '凉山州');
 insert into cities (id, province_id, name) values (239, 22, '成都市');
 insert into cities (id, province_id, name) values (240, 22, '自贡市');
 insert into cities (id, province_id, name) values (241, 22, '攀枝花市');
 insert into cities (id, province_id, name) values (242, 22, '泸州市');
 insert into cities (id, province_id, name) values (243, 22, '绵阳市');
 insert into cities (id, province_id, name) values (244, 22, '德阳市');
 insert into cities (id, province_id, name) values (245, 22, '广元市');
 insert into cities (id, province_id, name) values (246, 22, '遂宁市');
 insert into cities (id, province_id, name) values (247, 22, '内江市');
 insert into cities (id, province_id, name) values (248, 22, '乐山市');
 insert into cities (id, province_id, name) values (249, 22, '宜宾市');
 insert into cities (id, province_id, name) values (250, 22, '广安市');
 insert into cities (id, province_id, name) values (251, 22, '南充市');
 insert into cities (id, province_id, name) values (252, 22, '达州市');
 insert into cities (id, province_id, name) values (253, 22, '巴中市');
 insert into cities (id, province_id, name) values (254, 22, '雅安市');
 insert into cities (id, province_id, name) values (255, 22, '眉山市');
 insert into cities (id, province_id, name) values (256, 22, '资阳市');
 insert into cities (id, province_id, name) values (257, 22, '阿坝州');
 insert into cities (id, province_id, name) values (258, 22, '甘孜州');
 insert into cities (id, province_id, name) values (259, 23, '三亚市');
 insert into cities (id, province_id, name) values (260, 23, '文昌市');
 insert into cities (id, province_id, name) values (261, 23, '五指山市');
 insert into cities (id, province_id, name) values (262, 23, '临高县');
 insert into cities (id, province_id, name) values (263, 23, '澄迈县');
 insert into cities (id, province_id, name) values (264, 23, '定安县');
 insert into cities (id, province_id, name) values (265, 23, '屯昌县');
 insert into cities (id, province_id, name) values (266, 23, '昌江县');
 insert into cities (id, province_id, name) values (267, 23, '白沙县');
 insert into cities (id, province_id, name) values (268, 23, '琼中县');
 insert into cities (id, province_id, name) values (269, 23, '陵水县');
 insert into cities (id, province_id, name) values (270, 23, '保亭县');
 insert into cities (id, province_id, name) values (271, 23, '乐东县');
 insert into cities (id, province_id, name) values (272, 23, '三沙市');
 insert into cities (id, province_id, name) values (273, 23, '海口市');
 insert into cities (id, province_id, name) values (274, 23, '琼海市');
 insert into cities (id, province_id, name) values (275, 23, '万宁市');
 insert into cities (id, province_id, name) values (276, 23, '东方市');
 insert into cities (id, province_id, name) values (277, 23, '儋州市');
 insert into cities (id, province_id, name) values (278, 24, '贵阳市');
 insert into cities (id, province_id, name) values (279, 24, '六盘水市');
 insert into cities (id, province_id, name) values (280, 24, '遵义市');
 insert into cities (id, province_id, name) values (281, 24, '铜仁市');
 insert into cities (id, province_id, name) values (282, 24, '毕节市');
 insert into cities (id, province_id, name) values (283, 24, '安顺市');
 insert into cities (id, province_id, name) values (284, 24, '黔西南州');
 insert into cities (id, province_id, name) values (285, 24, '黔东南州');
 insert into cities (id, province_id, name) values (286, 24, '黔南州');
 insert into cities (id, province_id, name) values (287, 25, '迪庆州');
 insert into cities (id, province_id, name) values (288, 25, '昆明市');
 insert into cities (id, province_id, name) values (289, 25, '曲靖市');
 insert into cities (id, province_id, name) values (290, 25, '玉溪市');
 insert into cities (id, province_id, name) values (291, 25, '昭通市');
 insert into cities (id, province_id, name) values (292, 25, '普洱市');
 insert into cities (id, province_id, name) values (293, 25, '临沧市');
 insert into cities (id, province_id, name) values (294, 25, '保山市');
 insert into cities (id, province_id, name) values (295, 25, '丽江市');
 insert into cities (id, province_id, name) values (296, 25, '文山州');
 insert into cities (id, province_id, name) values (297, 25, '红河州');
 insert into cities (id, province_id, name) values (298, 25, '西双版纳州');
 insert into cities (id, province_id, name) values (299, 25, '楚雄州');
 insert into cities (id, province_id, name) values (300, 25, '大理州');
 insert into cities (id, province_id, name) values (301, 25, '德宏州');
 insert into cities (id, province_id, name) values (302, 25, '怒江州');
 insert into cities (id, province_id, name) values (303, 26, '阿里地区');
 insert into cities (id, province_id, name) values (304, 26, '林芝地区');
 insert into cities (id, province_id, name) values (305, 26, '拉萨市');
 insert into cities (id, province_id, name) values (306, 26, '那曲地区');
 insert into cities (id, province_id, name) values (307, 26, '山南地区');
 insert into cities (id, province_id, name) values (308, 26, '昌都地区');
 insert into cities (id, province_id, name) values (309, 26, '日喀则地区');
 insert into cities (id, province_id, name) values (310, 27, '延安市');
 insert into cities (id, province_id, name) values (311, 27, '汉中市');
 insert into cities (id, province_id, name) values (312, 27, '榆林市');
 insert into cities (id, province_id, name) values (313, 27, '商洛市');
 insert into cities (id, province_id, name) values (314, 27, '安康市');
 insert into cities (id, province_id, name) values (315, 27, '西安市');
 insert into cities (id, province_id, name) values (316, 27, '铜川市');
 insert into cities (id, province_id, name) values (317, 27, '宝鸡市');
 insert into cities (id, province_id, name) values (318, 27, '咸阳市');
 insert into cities (id, province_id, name) values (319, 27, '渭南市');
 insert into cities (id, province_id, name) values (320, 28, '庆阳市');
 insert into cities (id, province_id, name) values (321, 28, '陇南市');
 insert into cities (id, province_id, name) values (322, 28, '武威市');
 insert into cities (id, province_id, name) values (323, 28, '张掖市');
 insert into cities (id, province_id, name) values (324, 28, '酒泉市');
 insert into cities (id, province_id, name) values (325, 28, '甘南州');
 insert into cities (id, province_id, name) values (326, 28, '临夏州');
 insert into cities (id, province_id, name) values (327, 28, '定西市');
 insert into cities (id, province_id, name) values (328, 28, '兰州市');
 insert into cities (id, province_id, name) values (329, 28, '金昌市');
 insert into cities (id, province_id, name) values (330, 28, '白银市');
 insert into cities (id, province_id, name) values (331, 28, '天水市');
 insert into cities (id, province_id, name) values (332, 28, '嘉峪关市');
 insert into cities (id, province_id, name) values (333, 28, '平凉市');
 insert into cities (id, province_id, name) values (334, 29, '西宁市');
 insert into cities (id, province_id, name) values (335, 29, '海东地区');
 insert into cities (id, province_id, name) values (336, 29, '海北州');
 insert into cities (id, province_id, name) values (337, 29, '黄南州');
 insert into cities (id, province_id, name) values (338, 29, '海南州');
 insert into cities (id, province_id, name) values (339, 29, '果洛州');
 insert into cities (id, province_id, name) values (340, 29, '玉树州');
 insert into cities (id, province_id, name) values (341, 29, '海西州');
 insert into cities (id, province_id, name) values (342, 30, '银川市');
 insert into cities (id, province_id, name) values (343, 30, '石嘴山市');
 insert into cities (id, province_id, name) values (344, 30, '吴忠市');
 insert into cities (id, province_id, name) values (345, 30, '固原市');
 insert into cities (id, province_id, name) values (346, 30, '中卫市');
 insert into cities (id, province_id, name) values (347, 31, '五家渠市');
 insert into cities (id, province_id, name) values (348, 31, '阿拉尔市');
 insert into cities (id, province_id, name) values (349, 31, '图木舒克市');
 insert into cities (id, province_id, name) values (350, 31, '乌鲁木齐市');
 insert into cities (id, province_id, name) values (351, 31, '克拉玛依市');
 insert into cities (id, province_id, name) values (352, 31, '石河子市');
 insert into cities (id, province_id, name) values (353, 31, '吐鲁番地区');
 insert into cities (id, province_id, name) values (354, 31, '哈密地区');
 insert into cities (id, province_id, name) values (355, 31, '和田地区');
 insert into cities (id, province_id, name) values (356, 31, '阿克苏地区');
 insert into cities (id, province_id, name) values (357, 31, '喀什地区');
 insert into cities (id, province_id, name) values (358, 31, '克孜勒苏州');
 insert into cities (id, province_id, name) values (359, 31, '巴音郭楞州');
 insert into cities (id, province_id, name) values (360, 31, '昌吉州');
 insert into cities (id, province_id, name) values (361, 31, '博尔塔拉州');
 insert into cities (id, province_id, name) values (362, 31, '伊犁州');
 insert into cities (id, province_id, name) values (363, 31, '塔城地区');
 insert into cities (id, province_id, name) values (364, 31, '阿勒泰地区');
 insert into cities (id, province_id, name) values (365, 32, '台湾市');
 insert into cities (id, province_id, name) values (366, 33, '香港特别行政区');
 insert into cities (id, province_id, name) values (367, 34, '澳门市');
 insert into cities (id, province_id, name) values (1310, 15, '舟山新区');
 insert into cities (id, province_id, name) values (1311, 27, '西咸新区');
 insert into cities (id, province_id, name) values (1312, 31, '北屯');
 insert into cities (id, province_id, name) values (1313, 31, '铁门关');
 insert into cities (id, province_id, name) values (1314, 31, '双河');
 insert into cities (id, province_id, name) values (1315, 31, '可克达拉');
 insert into cities (id, province_id, name) values (1316, 31, '昆玉');
 insert into cities (id, province_id, name) values (1317, 32, '台北');
 insert into cities (id, province_id, name) values (1318, 32, '高雄');
 insert into cities (id, province_id, name) values (1319, 32, '基隆');
 insert into cities (id, province_id, name) values (1320, 32, '台中');
 insert into cities (id, province_id, name) values (1321, 32, '台南');
 insert into cities (id, province_id, name) values (1322, 32, '新竹');
 insert into cities (id, province_id, name) values (1323, 32, '嘉义');
 insert into cities (id, province_id, name) values (1324, 32, '新北');
 insert into cities (id, province_id, name) values (1325, 32, '宜兰');
 insert into cities (id, province_id, name) values (1326, 32, '桃园');
 insert into cities (id, province_id, name) values (1327, 32, '苗栗');
 insert into cities (id, province_id, name) values (1328, 32, '彰化');
 insert into cities (id, province_id, name) values (1329, 32, '南投');
 insert into cities (id, province_id, name) values (1330, 32, '云林');
 insert into cities (id, province_id, name) values (1331, 32, '屏东');
 insert into cities (id, province_id, name) values (1332, 32, '台东');
 insert into cities (id, province_id, name) values (1333, 32, '花莲');
 insert into cities (id, province_id, name) values (1334, 32, '澎湖');
 insert into cities (id, province_id, name) values (1335, 32, '金门');
 insert into cities (id, province_id, name) values (1336, 32, '连江');
 insert into cities (id, province_id, name) values (1337, 33, '香港岛');
 insert into cities (id, province_id, name) values (1338, 33, '九龙');
 insert into cities (id, province_id, name) values (1339, 33, '新界');
 insert into cities (id, province_id, name) values (1340, 34, '澳门半岛');
 insert into cities (id, province_id, name) values (1341, 34, '氹仔岛');
 insert into cities (id, province_id, name) values (1342, 34, '路环岛');


update provinces set latitude =    395500  , longitude =    1162400 where id =    1 ;
update provinces set latitude =    311400  , longitude =    1212900 where id =   2 ;
update provinces set latitude =    390200  , longitude =    1171200 where id =   3 ;
update provinces set latitude =    293500  , longitude =    1063300 where id =   4 ;
update provinces set latitude =    380200  , longitude =    1143000 where id =   5 ;
update provinces set latitude =    375400  , longitude =    1123300 where id =   6 ;
update provinces set latitude =    344600  , longitude =    1134000 where id =   7 ;
update provinces set latitude =    414799  , longitude =    1232500 where id =   8 ;
update provinces set latitude =    435400  , longitude =    1251900 where id =   9 ;
update provinces set latitude =    454400  , longitude =    1263600 where id =  10 ;
update provinces set latitude =    404799  , longitude =    1114100 where id =  11 ;
update provinces set latitude =    320300  , longitude =    1184600 where id =  12 ;
update provinces set latitude =    364000  , longitude =    1170000 where id =  13 ;
update provinces set latitude =    315200  , longitude =    1171700 where id =  14 ;
update provinces set latitude =    301600  , longitude =    1201000 where id =  15 ;
update provinces set latitude =    260500  , longitude =    1191800 where id =  16 ;
update provinces set latitude =    303500  , longitude =    1141700 where id =  17 ;
update provinces set latitude =    281200  , longitude =    1125900 where id =  18 ;
update provinces set latitude =    230799  , longitude =    1131400 where id =  19 ;
update provinces set latitude =    224800  , longitude =    1081900 where id =  20 ;
update provinces set latitude =    284000  , longitude =    1155500 where id =  21 ;
update provinces set latitude =    304000  , longitude =    1040400 where id =  22 ;
update provinces set latitude =    200200  , longitude =    1102000 where id =  23 ;
update provinces set latitude =    263500  , longitude =    1064200 where id =  24 ;
update provinces set latitude =    250400  , longitude =    1024200 where id =  25 ;
update provinces set latitude =    293900  , longitude =     910800 where id =  26 ;
update provinces set latitude =    341700  , longitude =    1085700 where id =  27 ;
update provinces set latitude =    360400  , longitude =    1035100 where id =  28 ;
update provinces set latitude =    363800  , longitude =    1014800 where id =  29 ;
update provinces set latitude =    382700  , longitude =    1061600 where id =  30 ;
update provinces set latitude =    434500  , longitude =     873600 where id =  31 ;
update provinces set latitude =    250300  , longitude =    1213000 where id =  32 ;
update provinces set latitude =    212300  , longitude =    1151200 where id =  33 ;
update provinces set latitude =    213299  , longitude =    1150700 where id =  34 ;
